In [1]:
import numpy as np

### Create array

# Numerical Python

In [2]:
def list_arr(list1):
    '''
    Convert list the array
    '''
    arr = np.array(list1)
    return arr

In [3]:
list1 = [1, 2, 3, 4]

arr = list_arr(list1)

print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [6]:
def even_array(lst):
    '''
    Convert only even items to array
    '''
    return np.array([i for i in lst if i % 2 == 0])

In [7]:
list1 = [1, 2, 3, 4]

arr = even_array(list1)

print(arr)

[2 4]


## Numpy array properties


In [8]:
def arry_1D():
    '''
    Create any 1D array
    '''
    lst = []
    # CODE
    for i in range(10):
        lst.append(i)
    return np.array(lst)

In [14]:
arr = arry_1D()

print(arr)
print(arr.shape)
print(arr.ndim)

[0 1 2 3 4 5 6 7 8 9]
(10,)
1


In [11]:
def arry_2D():
    '''
    Create any 2D array
    '''
    lst = []
    # CODE
    for i in range(10):
        row = []
        for j in range(10):
            row.append(j)
        lst.append(row)
    return np.array(lst)

In [15]:
arr = arry_2D()

print(arr)
print(arr.shape)
print(arr.ndim)

[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]
(10, 10)
2


In [16]:
def arry_3D():
    '''
    Create any 3D array
    '''
    lst = []
    # CODE
    for i in range(5):
        row = []
        for j in range(5):
            rowin = []
            for k in range(5):
                rowin.append(k)
            row.append(rowin)
        lst.append(row)
    return np.array(lst)

In [17]:
arr = arry_3D()

print(arr)
print(arr.shape)
print(arr.ndim)

[[[0 1 2 3 4]
  [0 1 2 3 4]
  [0 1 2 3 4]
  [0 1 2 3 4]
  [0 1 2 3 4]]

 [[0 1 2 3 4]
  [0 1 2 3 4]
  [0 1 2 3 4]
  [0 1 2 3 4]
  [0 1 2 3 4]]

 [[0 1 2 3 4]
  [0 1 2 3 4]
  [0 1 2 3 4]
  [0 1 2 3 4]
  [0 1 2 3 4]]

 [[0 1 2 3 4]
  [0 1 2 3 4]
  [0 1 2 3 4]
  [0 1 2 3 4]
  [0 1 2 3 4]]

 [[0 1 2 3 4]
  [0 1 2 3 4]
  [0 1 2 3 4]
  [0 1 2 3 4]
  [0 1 2 3 4]]]
(5, 5, 5)
3


### The shape of the array
 **shape**  - Return the shape of an array.					
 **Returns**: tuple of ints



In [18]:
def arry_3x3():
    '''
    Create any 3x3 array
    '''
    lst = []
    # CODE
    for i in range(3):
        row = []
        for j in range(3):
            row.append(j)
        lst.append(row)
    return np.array(lst)

In [19]:
arr = arry_3x3()

print(arr)
print(arr.shape)
print(arr.ndim)

[[0 1 2]
 [0 1 2]
 [0 1 2]]
(3, 3)
2


In [24]:
def arry_2x3():
    '''
    Create lst to 2x3 array
    return 1D
    '''
    lst = []
    # CODE
    for i in range(2):
        row = []
        for j in range(3):
            row.append(j)
        lst.append(row)
    return np.array(lst)

In [25]:
arr = arry_2x3()

print(arr)
print(arr.shape)
print(arr.ndim)

[[0 1 2]
 [0 1 2]]
(2, 3)
2


## The dtype of the array


### np.int8

In [36]:
def array_dtype_int8(n):
    '''
    Create an array dtype int8
    return nD array
    '''
    return np.full([n] * n, fill_value=n, dtype=np.int8)

In [38]:
arr = array_dtype_int8(3)

print(arr)
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

[[[3 3 3]
  [3 3 3]
  [3 3 3]]

 [[3 3 3]
  [3 3 3]
  [3 3 3]]

 [[3 3 3]
  [3 3 3]
  [3 3 3]]]
int8
(3, 3, 3)
3


### np.int16

In [40]:
def array_dtype_int16(n):
    '''
    Create an array dtype int16
    return nD array
    '''
    return np.full([n] * n, fill_value=n, dtype=np.int16)

In [41]:
arr = array_dtype_int16(3)

print(arr)
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

[[[3 3 3]
  [3 3 3]
  [3 3 3]]

 [[3 3 3]
  [3 3 3]
  [3 3 3]]

 [[3 3 3]
  [3 3 3]
  [3 3 3]]]
int16
(3, 3, 3)
3


### np.float

In [44]:
def array_dtype_float(n):
    '''
    Create an array dtype float
    return nD array
    '''
    return np.full([n] * n, fill_value=n, dtype=np.float64)

In [45]:
arr = array_dtype_float(3)

print(arr)
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

[[[3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]]

 [[3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]]

 [[3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]]]
float64
(3, 3, 3)
3


### np.bool

In [46]:
def array_dtype_bool(n):
    '''
    Create array dtype bool
    return nD array
    '''
    return np.full([n] * n, fill_value=n, dtype=np.bool_)

In [47]:
arr = array_dtype_bool(3)

print(arr)
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

[[[ True  True  True]
  [ True  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True  True]
  [ True  True  True]]]
bool
(3, 3, 3)
3


# Creating Arrays

### np.arange

In [48]:
def arange_1D_arr():
    '''
    Create any 1D array
    return array
    '''
    return np.arange(10)

In [50]:
arr = arange_1D_arr()

print(arr)
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

[0 1 2 3 4 5 6 7 8 9]
int32
(10,)
1


In [51]:
def arrange_array(n):
    '''
    Create any array from 0 to n
    return array
    '''
    return np.arange(n)

In [53]:
arr = arrange_array(10)

print(arr)
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

[0 1 2 3 4 5 6 7 8 9]
int32
(10,)
1


### np.linspace

In [54]:
def linspace_arr(n):
    '''
    Create an array of the range 0 and n divided by 10
    return array
    '''
    return np.linspace(0, n, num=10)

In [55]:
arr = linspace_arr(33)

print(arr)
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

[ 0.          3.66666667  7.33333333 11.         14.66666667 18.33333333
 22.         25.66666667 29.33333333 33.        ]
float64
(10,)
1


### np.zeros

In [58]:
def array_zeros_nxm(n, m):
    '''
    Create an nxm array of zeros
    return array
    '''
    return np.zeros((n, m))

In [59]:
arr = array_zeros_nxm(3, 5)

print(arr)
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
float64
(3, 5)
2


In [63]:
def array_zeros_3D():
    '''
    Create any an 3D array of zeros
    return 3D array
    '''
    return np.zeros((3, 3, 3))

In [64]:
arr = array_zeros_3D()

print(arr)
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
float64
(3, 3, 3)
3


### np.ones

In [65]:
def array_ones_nxm(n, m):
    '''
    Create an nxm array of ones
    return array
    '''
    return np.ones((n, m))

In [66]:
arr = array_ones_nxm(3, 5)

print(arr)
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
float64
(3, 5)
2


### np.full

In [67]:
def array_full_3D(n, m, k):
    '''
    Create any an 3D array of seven, shape = (n,m,k)
    return 3D array
    '''
    return np.full((n, m, k), fill_value=7)

In [68]:
arr = array_full_3D(3, 5, 4)

print(arr)
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

[[[7 7 7 7]
  [7 7 7 7]
  [7 7 7 7]
  [7 7 7 7]
  [7 7 7 7]]

 [[7 7 7 7]
  [7 7 7 7]
  [7 7 7 7]
  [7 7 7 7]
  [7 7 7 7]]

 [[7 7 7 7]
  [7 7 7 7]
  [7 7 7 7]
  [7 7 7 7]
  [7 7 7 7]]]
int32
(3, 5, 4)
3


In [69]:
!git add "NumPy_Homework.ipynb"

In [70]:
!git commit -m "Numpy Part I"

[django-first 416774a] Numpy Part I
 1 file changed, 187 insertions(+), 8 deletions(-)


In [71]:
!git push

To https://github.com/Mr-Umidjon/01-Numpy.git
   9d7254e..416774a  django-first -> django-first
